use crate::export;
use crate::metrics::Metrics;
use crate::simulation::lenia::LeniaSim;
use crate::simulation::life::LifeSim;
use crate::simulation::reaction_diffusion::ReactionDiffusionSim;
use crate::simulation::{RenderStyle, SimMode};
use egui::{Color32, ColorImage, TextureHandle, TextureOptions};
use std::time::{Duration, Instant};

pub struct PeterMathApp {
    mode: SimMode,
    render_style: RenderStyle,
    lenia: LeniaSim,
    reaction: ReactionDiffusionSim,
    life: LifeSim,
    running: bool,
    judge_mode: bool,
    steps_per_frame: usize,
    step_count: u64,
    pixels: Vec<u8>,
    texture: Option<TextureHandle>,
    status: String,
    last_tick: Instant,
}

impl PeterMathApp {
    pub fn new(cc: &eframe::CreationContext<'_>) -> Self {
        configure_style(&cc.egui_ctx);
        let width = 192;
        Self {
            mode: SimMode::Lenia,
            render_style: RenderStyle::Artistic,
            lenia: LeniaSim::new(width, width, 1001),
            reaction: ReactionDiffusionSim::new(width, width, 2001),
            life: LifeSim::new(160, 160, 3001),
            running: true,
            judge_mode: false,
            steps_per_frame: 1,
            step_count: 0,
            pixels: vec![0; width * width * 4],
            texture: None,
            status: "Ready. Tune one rule and watch form, motion, and metrics agree.".to_owned(),
            last_tick: Instant::now(),
        }
    }

    fn active_size(&self) -> (usize, usize) {
        match self.mode {
            SimMode::Lenia => self.lenia.size(),
            SimMode::ReactionDiffusion => self.reaction.size(),
            SimMode::GameOfLife => self.life.size(),
        }
    }

    fn active_seed(&self) -> u64 {
        match self.mode {
            SimMode::Lenia => self.lenia.seed,
            SimMode::ReactionDiffusion => self.reaction.seed,
            SimMode::GameOfLife => self.life.seed,
        }
    }

    fn active_metrics(&self) -> Metrics {
        match self.mode {
            SimMode::Lenia => self.lenia.metrics(),
            SimMode::ReactionDiffusion => self.reaction.metrics(),
            SimMode::GameOfLife => self.life.metrics(),
        }
    }

    fn reset_active(&mut self) {
        self.step_count = 0;
        match self.mode {
            SimMode::Lenia => self.lenia.reset_preset("orbital_field"),
            SimMode::ReactionDiffusion => self.reaction.reset_preset("mitosis"),
            SimMode::GameOfLife => self.life.reset_preset("symmetric_seed"),
        }
    }

    fn step_active(&mut self) {
        match self.mode {
            SimMode::Lenia => self.lenia.step(),
            SimMode::ReactionDiffusion => self.reaction.step(),
            SimMode::GameOfLife => self.life.step(),
        }
        self.step_count += 1;
    }

    fn render_active(&mut self) -> (usize, usize) {
        let (w, h) = self.active_size();
        let required = w * h * 4;
        if self.pixels.len() != required {
            self.pixels.resize(required, 0);
        }
        match self.mode {
            SimMode::Lenia => self.lenia.render_rgba(self.render_style, &mut self.pixels),
            SimMode::ReactionDiffusion => self
                .reaction
                .render_rgba(self.render_style, &mut self.pixels),
            SimMode::GameOfLife => self.life.render_rgba(self.render_style, &mut self.pixels),
        }
        (w, h)
    }

    fn export_snapshot(&mut self) {
        let (w, h) = self.render_active();
        let stem = format!(
            "peterMath_{:?}_seed{}_step{}",
            self.mode,
            self.active_seed(),
            self.step_count
        );
        let png_path = format!("{}_snapshot.png", stem);
        let json_path = format!("{}_parameters.json", stem);
        let metrics = self.active_metrics();
        let result = (|| -> anyhow::Result<()> {
            export::save_png(&png_path, w, h, &self.pixels)?;
            export::save_json(
                &json_path,
                self.mode.label(),
                self.render_style.label(),
                self.active_seed(),
                self.step_count,
                metrics,
            )?;
            Ok(())
        })();
        self.status = match result {
            Ok(()) => format!("Exported {} and {}", png_path, json_path),
            Err(err) => format!("Export failed: {err}"),
        };
    }

    fn draw_left_panel(&mut self, ui: &mut egui::Ui) {
        ui.heading("peterMath");
        ui.label("Computational artwork from mathematical rules");
        ui.small("Beauty is generated by fields, kernels, diffusion, and deterministic seeds.");
        ui.separator();

        egui::ComboBox::from_label("System")
            .selected_text(self.mode.label())
            .show_ui(ui, |ui| {
                ui.selectable_value(&mut self.mode, SimMode::Lenia, "Lenia-like field");
                ui.selectable_value(
                    &mut self.mode,
                    SimMode::ReactionDiffusion,
                    "Reaction-Diffusion",
                );
                ui.selectable_value(&mut self.mode, SimMode::GameOfLife, "Game of Life");
            });

        egui::ComboBox::from_label("View")
            .selected_text(self.render_style.label())
            .show_ui(ui, |ui| {
                ui.selectable_value(
                    &mut self.render_style,
                    RenderStyle::RawMath,
                    "Raw Math View",
                );
                ui.selectable_value(
                    &mut self.render_style,
                    RenderStyle::Artistic,
                    "Artistic View",
                );
            });

        ui.checkbox(&mut self.judge_mode, "Judge Mode");
        ui.add(egui::Slider::new(&mut self.steps_per_frame, 1..=20).text("steps / frame"));

        ui.horizontal(|ui| {
            if ui
                .button(if self.running { "Pause" } else { "Run" })
                .clicked()
            {
                self.running = !self.running;
            }
            if ui.button("Step").clicked() {
                self.step_active();
            }
            if ui.button("Reset").clicked() {
                self.reset_active();
            }
        });

        if ui.button("Export snapshot + parameters").clicked() {
            self.export_snapshot();
        }

        ui.separator();
        ui.label(format!("Mode: {}", self.mode.label()));
        ui.label(format!("Seed: {}", self.active_seed()));
        ui.label(format!("Step: {}", self.step_count));
        ui.label(format!("Frame: {}", self.mode_statement()));
        ui.label(&self.status);
    }

    fn draw_right_panel(&mut self, ui: &mut egui::Ui) {
        ui.heading("Parameters");
        match self.mode {
            SimMode::Lenia => {
                let mut radius = self.lenia.radius as u32;
                if ui
                    .add(egui::Slider::new(&mut radius, 3..=32).text("kernel radius"))
                    .changed()
                {
                    self.lenia.set_radius(radius as usize);
                }
                ui.add(
                    egui::Slider::new(&mut self.lenia.growth_center, 0.05..=0.95)
                        .text("growth center"),
                );
                ui.add(
                    egui::Slider::new(&mut self.lenia.growth_width, 0.005..=0.18)
                        .text("growth width"),
                );
                ui.add(egui::Slider::new(&mut self.lenia.dt, 0.005..=0.25).text("time step"));
                ui.add(egui::Slider::new(&mut self.lenia.decay, 0.0..=0.04).text("damping"));
                ui.label("Rule: a continuous field grows according to a weighted neighborhood kernel and a bell-shaped growth curve.");
            }
            SimMode::ReactionDiffusion => {
                ui.add(egui::Slider::new(&mut self.reaction.feed, 0.005..=0.09).text("feed"));
                ui.add(egui::Slider::new(&mut self.reaction.kill, 0.02..=0.09).text("kill"));
                ui.add(
                    egui::Slider::new(&mut self.reaction.diff_a, 0.02..=0.30).text("diffusion A"),
                );
                ui.add(
                    egui::Slider::new(&mut self.reaction.diff_b, 0.005..=0.20).text("diffusion B"),
                );
                ui.add(egui::Slider::new(&mut self.reaction.dt, 0.2..=1.5).text("time step"));
                ui.label("Rule: two virtual chemicals diffuse and react. Feed/kill parameters control spots, waves, and labyrinths.");
            }
            SimMode::GameOfLife => {
                ui.add(
                    egui::Slider::new(&mut self.life.random_density, 0.02..=0.55)
                        .text("seed density"),
                );
                if ui.button("Random deterministic seed").clicked() {
                    self.life.reset_random();
                    self.step_count = 0;
                }
                ui.label("Rule B3/S23: birth with 3 neighbors; survival with 2 or 3 neighbors.");
            }
        }

        ui.separator();
        ui.heading("Metrics");
        let m = self.active_metrics();
        metric_bar(ui, "mass/activity", m.mass);
        metric_bar(ui, "entropy", m.entropy);
        metric_bar(ui, "symmetry", m.symmetry);
        metric_bar(ui, "stability", m.stability);
        metric_bar(ui, "vitality", m.vitality);
        ui.label(format!("active cells/pixels: {}", m.active));

        ui.separator();
        ui.heading("Mathematical Frame");
        ui.label(self.mode_formula());
        ui.small(self.mode_significance());

        if self.judge_mode {
            ui.separator();
            ui.heading("Judge Mode Guide");
            ui.label("1. Start with Raw Math View to show the data field.");
            ui.label("2. Run 100 steps and watch metrics change.");
            ui.label("3. Change one parameter only.");
            ui.label("4. Compare the new pattern and export evidence.");
        }
    }

    fn mode_statement(&self) -> &'static str {
        match self.mode {
            SimMode::Lenia => "continuous field life",
            SimMode::ReactionDiffusion => "chemical pattern formation",
            SimMode::GameOfLife => "discrete local rule",
        }
    }

    fn mode_formula(&self) -> &'static str {
        match self.mode {
            SimMode::Lenia => "u[t+1] = clamp(u[t] + dt * G(K * u[t]) - damping * u[t])",
            SimMode::ReactionDiffusion => "A,B diffuse locally while A + 2B -> 3B reacts.",
            SimMode::GameOfLife => "B3/S23: birth at 3 neighbors; survive at 2 or 3.",
        }
    }

    fn mode_significance(&self) -> &'static str {
        match self.mode {
            SimMode::Lenia => "A soft neighborhood kernel turns small numeric changes into organism-like motion.",
            SimMode::ReactionDiffusion => "Competing diffusion and reaction rates reveal spots, membranes, waves, and labyrinths.",
            SimMode::GameOfLife => "A simple grid rule explains the bridge from discrete cells to continuous fields.",
        }
    }
}

impl eframe::App for PeterMathApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        if self.running {
            let elapsed = self.last_tick.elapsed();
            if elapsed >= Duration::from_millis(66) {
                for _ in 0..self.steps_per_frame {
                    self.step_active();
                }
                self.last_tick = Instant::now();
                ctx.request_repaint();
            } else {
                ctx.request_repaint_after(Duration::from_millis(66) - elapsed);
            }
        }

        egui::TopBottomPanel::top("top_bar").show(ctx, |ui| {
            ui.horizontal(|ui| {
                ui.strong("peterMath");
                ui.separator();
                ui.label("mathematical life-system laboratory");
                ui.separator();
                ui.label(self.mode.label());
                ui.separator();
                ui.label(self.render_style.label());
                ui.separator();
                ui.label(format!("seed {}", self.active_seed()));
                ui.separator();
                ui.label(format!("step {}", self.step_count));
            });
        });

        egui::SidePanel::left("left_controls")
            .resizable(false)
            .default_width(260.0)
            .show(ctx, |ui| self.draw_left_panel(ui));

        egui::SidePanel::right("right_parameters")
            .resizable(false)
            .default_width(330.0)
            .show(ctx, |ui| self.draw_right_panel(ui));

        egui::CentralPanel::default().show(ctx, |ui| {
            let (w, h) = self.render_active();
            let image = ColorImage::from_rgba_unmultiplied([w, h], &self.pixels);
            if let Some(texture) = &mut self.texture {
                texture.set(image, TextureOptions::LINEAR);
            } else {
                self.texture =
                    Some(ctx.load_texture("peterMath-field", image, TextureOptions::LINEAR));
            }

            if let Some(texture) = &self.texture {
                let available = ui.available_size();
                let square = (available.x.min(available.y) - 28.0).max(320.0);
                let size = egui::vec2(square, square);
                ui.vertical_centered(|ui| {
                    ui.add_space(8.0);
                    egui::Frame::canvas(ui.style()).show(ui, |ui| {
                        ui.image((texture.id(), size));
                    });
                    ui.add_space(8.0);
                    ui.small(format!(
                        "{} | {} | seed {} | step {}",
                        self.mode.label(),
                        self.render_style.label(),
                        self.active_seed(),
                        self.step_count
                    ));
                });
            }
        });
    }
}

fn configure_style(ctx: &egui::Context) {
    let mut style = (*ctx.style()).clone();
    style.visuals = egui::Visuals::dark();
    style.visuals.panel_fill = Color32::from_rgb(12, 16, 18);
    style.visuals.window_fill = Color32::from_rgb(9, 12, 14);
    style.visuals.extreme_bg_color = Color32::from_rgb(4, 6, 7);
    style.visuals.widgets.noninteractive.bg_fill = Color32::from_rgb(18, 24, 27);
    style.visuals.widgets.inactive.bg_fill = Color32::from_rgb(24, 32, 36);
    style.visuals.selection.bg_fill = Color32::from_rgb(60, 116, 106);
    style.spacing.item_spacing = egui::vec2(8.0, 8.0);
    style.spacing.slider_width = 170.0;
    ctx.set_style(style);
}

fn metric_bar(ui: &mut egui::Ui, label: &str, value: f32) {
    ui.horizontal(|ui| {
        ui.label(label);
        ui.add(egui::ProgressBar::new(value.clamp(0.0, 1.0)).show_percentage());
    });
}
